sudo: required

language: node_js

node_js:
  - "4.1"

services:
  - docker
  - postgresql

install:
  - docker build -t stefaneng/partyq .
  - docker ps -a
  - docker run -d -p 127.0.0.1:80:3000 stefaneng/partyq /bin/sh -c 'npm start'

before_script:
  - psql -c 'create database partyqtest;' -U postgres

script:
  - docker run stefaneng/partyq /bin/sh -c 'npm run lint'
  - docker run stefaneng/partyq /bin/sh -c 'npm test'
  - curl -i localhost
